databases:
  - name: budget
    plan: free
    databaseName: budget_2fvx
    user: budget_user

services:
  - type: web
    plan: free
    name: budget_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false